project:
  name: cfn-abi-aws-reference-guide
  owner: vinjak@amazon.com
  package_lambda: true
  shorten_stack_name: true
  s3_regional_buckets: false
  regions:
  - us-east-1

tests:
  launch-partner-solution:
    parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAStagingS3Key: $[taskcat_project_name]
      pProductArn: arn:aws:securityhub:$[taskcat_current_region]::product/cloud-custodian/cloud-custodian
    regions:
      - us-east-1
    template: templates/abi-enable-partner1-securityhub-integration.yaml

  launch-partner-solution-nonct:
    parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAStagingS3Key: $[taskcat_project_name]
      pProductArn: arn:aws:securityhub:$[taskcat_current_region]::product/cloud-custodian/cloud-custodian
      pControlTower: "false"
      pGovernedRegions: "us-east-1,us-west-1"
      pSecurityAccountId: "809545598792"
      pLogArchiveAccountId: "866786363886"
      pCreateAWSControlTowerExecutionRole: "true"
    regions:
      - us-east-1
    template: templates/abi-enable-partner1-securityhub-integration.yaml
#  sample:
#    parameters:
#      Param1: 'Inputs to Stack'
#      # Examples: of other taskcat dynamic input parameters for more into see http://taskcat.io
#      #
#      #      AvailabilityZones: $[taskcat_genaz_3]
#      #      ByteValue: 1
#      #      PasswordA: $[taskcat_genpass_8A]
#      #      PasswordB: $[taskcat_genpass_32S]
#      #      RandomNumber: $[taskcat_random-numbers]
#      #      RandomString: $[taskcat_random-string]
#      #      StackName: TestStack
#      #      UUID: $[taskcat_genuuid]
#      #
#    regions:
#    - us-east-1
#    template: templates/sample-workload.template.yaml
