diff a/.project_automation/publication/Dockerfile b/.project_automation/publication/Dockerfile	(rejected hunks)
@@ -2,2 +2,3 @@ FROM public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:4.0
 RUN yum install -y yum-utils && yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo && yum install -y gh 
-RUN pip install taskcat
+RUN git clone https://github.com/aws-ia/taskcat.git -b fix_s3_upload /tmp/taskcat && cd /tmp/taskcat && pip install .
+#RUN pip install taskcat
