# https://gohugo.io/about/security-model/#security-policy
# https://stackoverflow.com/questions/71058236/hugo-with-asciidoctor

enableInlineShortcodes = false

[exec]
allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|RUBYLIB)$']

[funcs]
getenv = ['^HUGO_', '^CI$']

[http]
methods = ['(?i)GET|POST']
urls = ['.*']
